settings.render = -4 ;
settings.prc = false ;
import biblioLiaisons ;
defaultpen(fontsize(10pt)) ;
unitsize(1cm) ;
triple eye = (1,0,0) ;
triple up = (0,0,1) ;
currentprojection = orthographic(eye, up, O) ;
currentlight = nolight ;
simpleCubeBounding(1.5) ;
showBasis(b0, O, coeff=1.5*(1,1,1)) ;
addUshape(O-0.75*b0.y, b0.x, b0.y, 1.25, 1.75, 0.75, deepgreen) ;
namePoint(O-0.75*b0.y, "C", (-1,0)) ;